apply plugin: 'com.android.application'

android {

    namespace 'com.boardgames.bastien.schotten_totten'

    buildFeatures {
        viewBinding true
    }

    signingConfigs {
        release {
            def keystorePropertiesFile = rootProject.file('keystore.properties')
            if (keystorePropertiesFile.exists()) {
                def keystoreProperties = new Properties()
                keystoreProperties.load(new FileInputStream(keystorePropertiesFile))

                storeFile = file(keystoreProperties['storeFile'])
                storePassword = keystoreProperties['storePassword']
                keyAlias = keystoreProperties['keyAlias']
                keyPassword = keystoreProperties['keyPassword']
            }
        }
    }

    buildTypes {
        release {
            signingConfig signingConfigs.release
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    testOptions {
        unitTests.all {
            useJUnitPlatform()
        }
    }

    compileSdkVersion 37
    defaultConfig {
        multiDexEnabled true
        applicationId "com.boardgames.bastien.schotten_totten"
        minSdk 26
        targetSdk 37
        versionCode 50
        versionName '5.0'
        testInstrumentationRunner 'androidx.test.runner.AndroidJUnitRunner'
    }

    productFlavors {
    }
    packagingOptions {
        jniLibs {
            excludes += ['META-INF/*']
        }
        resources {
            excludes += ['META-INF/*']
        }
    }

    compileOptions {
    }
}

dependencies {
    implementation 'androidx.appcompat:appcompat:1.8.0'
    implementation 'androidx.legacy:legacy-support-v13:1.0.0'
    implementation 'com.google.android.material:material:1.14.0'
    testImplementation 'org.junit.jupiter:junit-jupiter-api:5.14.4'
    testRuntimeOnly 'org.junit.jupiter:junit-jupiter-engine:5.14.4'
    implementation 'org.apache.commons:commons-collections4:4.6.0'
    implementation 'org.apache.commons:commons-math3:3.6.1'
    implementation 'org.springframework.android:spring-android-rest-template:1.0.1.RELEASE'
    implementation 'com.fasterxml.jackson.core:jackson-databind:2.22.2'
    implementation 'org.springframework.android:spring-android-core:1.0.1.RELEASE'
    implementation 'org.nanohttpd:nanohttpd-nanolets:2.3.1'
    dependencies {
        implementation('com.github.schotten-totten-company:schotten-totten-core:2.0.2') {
            changing = true
        }
    }
}
